### ISSUE TITLE
Consistency of (Array) Axioms

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#111]
_(follows on from #102 and #105)_

This thread follows on from the initial discussion raised by @Utting regarding inconsistency of array axioms.  To make this work for me, I need a way of understanding (in)consistency.  This issue is a record of my thought process.

Roughly speaking, Mark is concerned as to whether or not our axioms in general are _consistent_.  Initially, we have focused on this axiom:

```
axiom (forall a:[int]Any,i:int,v:Any :: Array#Length(a) == Array#Length(a[i:=v])); 
```

In English, this says: _for any map "a", the length of "a" equals the length of "a[i:=v]"._

At first glance, the axiom seems innocuous. Whilst `Array#Length()` is uninterpreted, but we should imagine _some_
consistent implementation.  For example, we expect that if `x == y` then `Array#Length(x) == Array#Length(y)`, etc.

Let us imagine an implementation which suffices here (i.e. a model). Specifically, for a given map `[int]Any`,  `Array#Length()` returns the index of the first element containing `Void` (starting from zero).  If our map is all `Void` then it returns `0`, etc.  This model allows for maps which are not a single contiguous region of non-`Void` elements. 

Now comes the issue Mark identified.  Suppose two maps:

```
M0 = \x -> Void (i.e. the empty map) 
M1 = \x -> if(x == 0) { 0 } else { Void }
```

We have `Array#Length(M0) == 0` and `Array#Length(M1) == 1` (that's fine).  Unfortunately, our axiom above requires that `Array#Length(M1) == Array#Length(M1[i:=v])` for any `v` (e.g. including `Void`).  Since `M0 == M1[0:=v]` we have an inconsistency as `Array#Length(M0) != Array#Length(M1[i:=v])` follows.

**Comment by DavePearce** [comment]
At this point, we want to use this approach to reason about our axioms and root out any more problems.  We can fix the above problem by updating the above axiom as follows:

```
axiom (forall a:[int]Any,i:int,v:Any :: (v != Void) ==> (Array#Length(a) == Array#Length(a[i:=v]))); 
```

_But, is that enough?_

Mark suggests that we need guards to ensure `i` is within bounds.  Yes, the model suggests we do.  In particular, since `M0[0:=0] == M1` and, hence, `Array#length()` cannot be the same.  That lets be arrive at the final version of the axiom:

```
axiom (forall a:[int]Any,i:int,v:Any :: ((v != Void) && Array#in(a,i)) ==> (Array#Length(a) == Array#Length(a[i:=v])));
```
(where `Array#in(a,i)` requires that `i` is within bounds of `a`).

**Comment by DavePearce** [comment]
There are four other axioms which seem potentially suspect:

```
(1) axiom (forall a:[int]Any,l:int :: (Array#Empty(l) != a) || (Array#Length(a) == l));
```
```
(2) axiom (forall v:Any,l:int,i:int :: (i < 0) || (l <= i) || (Array#Generator(v,l)[i] == v));
```
```
(3) axiom (forall v:Any,l:int,i:int :: ((0 <= i) && (i < l)) || (Array#Generator(v,l)[i] == Void));
```
```
(4) axiom (forall a:[int]Any,v:Any,l:int :: (Array#Generator(v,l) != a) || (Array#Length(a) == l));
```
_So, do we need to update any of these?_  Yes, I think we do.  Here is my analysis:

### Axiom (1)

### Axiom (2)

### Axiom (3)

### Axiom (4)

**Comment by DavePearce** [comment]
Do we have another issue with `Array#Empty()`?  Consider these two axioms together:

```
axiom (forall l:int,i:int :: ((0 <= i) && (i < l)) || (Array#Empty(l)[i] == Void));
axiom (forall a:[int]Any,l:int :: (0 <= l && Array#Empty(l) == a) ==> (Array#Length(a) == l));
```

There is nothing stopping `Arrray#Empty()` from assigning `Void` to an element within bounds, and this would lead to inconsistency with `Array#Length()` ?

**Comment by utting** [comment]
Yes, I think these updated axioms are all consistent with the following implementation:

Array#Length returns the index (>=0) of the first Void entry in the map.
Array#Empty(n) creates a map where indices 0..(n-1) map to some arbitrary value (say 42), and all other indexes give Void.
    - so it really creates a fixed length array of *unknown* values, rather than an empty array (length 0), but that's fine.
Array#Generator(n,v) does the same, but uses v as the fill value, rather than 42.
   - but to be more precise, if v==Void, then it uses some other fill value, such as 42.

a[i := v] just updates index i (as defined by Boogie map semantics).
   - so for our length function to still return the same result, we have to insist that i is in range and v is not Void.

I think this implementation satisfies all the above axioms, showing that they are consistent.
And I agree that it does not require axioms 4 and 5 to have the v!=Void condition.

If this makes three tests fail, I'd be interested to know which ones?

**Comment by DavePearce** [comment]
Hey Mark,

Yeah, its not super satisfactory that its hard for us to decide if they are consistent.  I wonder if I can apply Whiley and model check them to see whether anything comes ... hmmmm.

The tests are `Template_Valid_22`, `Template_Valid_23` and `Template_Valid_29`.  I would assume it's the same problem.  The smallest one is this:

```
function f<T>(T[] arr) -> T[]:
    //
    return []

function g<T>(T[] arr, T def) -> T[]:
    //
    return [def; |arr|]

public export method test():
    //
    assume f([1,2,3]) == []
    assume f([true,false]) == []
    //
    assume g([],0) == []
    assume g([1,2,3],0) == [0,0,0]
    assume g([true,false],false) == [false,false]
```

I haven't had a chance to diagnose this yet.  I will probably do more work on the paper first though, since I want to get that into as good a shape as possible before I get sucked back into coding :)

**Comment by DavePearce** [comment]
Right, this is the smallest example from `Template_Valid_22` which illustrates the problem:

```
function g<T>(T def) -> T[]:
    //
    return [def; 1]
```

Observe that returning `[def; 0]` or just `[def]` and there is no problem.  This is clearly something to do with array generators.

**Comment by DavePearce** [comment]
Problem here is that, within the body of `g()` we cannot conclude that `def != Void`.
