### ISSUE TITLE
Typechecker loses precision?

### ISSUE THREAD

**Issue by utting** [Whiley/Whiley2Boogie#117]
The following line of code gives a type error::

    (casino.msg.sender, casino.address, casino.pot) = (transfer(casino.msg.sender, casino.address, value), casino.pot - value)

$ wy build
.\src\casino.whiley:252: expected (Address,Address,uint256), found ((Address,Address),int)
    (casino.msg.sender, casino.address, casino.pot) = (transfer(casino.msg.sender, casino.address, value), casino.pot - value)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

But flattening that line to do the call first gets rid of the type error::

    Address a1
    Address a2
    (a1, a2) = transfer(casino.msg.sender, casino.address, value)
    (casino.msg.sender, casino.address, casino.pot) = (a1, a2, casino.pot - value)

This seems strange, since the context is unchanged: value and casino.pot are both uint256.
And we have requires value > 0 && value <= casino.pot,
which should be enough (in both cases) to ensure that casino.pot - value is still uint256.

The two full versions of the program are:

[casino_uint256_type_error.whiley.txt](https://github.com/Whiley/Whiley2Boogie/files/6497669/casino_uint256_type_error.whiley.txt)
[casino_fixed.whiley.txt](https://github.com/Whiley/Whiley2Boogie/files/6497670/casino_fixed.whiley.txt)

**Comment by utting** [comment]
Ah, I see that the problem is probably the associativity, rather than the uint256 vs int issue.

Does this mean that there is no way of using a multi-return function in an expression other than by itself?
That is, given a function f() that returns (int,int), I cannot use it in an assignment like:

   r.a, r.b, r.c = f(), 3

(Let's say that all three fields of r need to be assigned simultaneously in order to preserve the invariant of r.)

**Comment by DavePearce** [comment]
Hey Mark,

Sorry this is a bit late.  But, yes you can do what you are asking:

```
function f() -> (int a, int b):
    return 0,1
    
method main():
    int a
    int b
    int c
    //
    (a,b),c = f(),0
```

Its just about the braces and where you put them.

**Comment by utting** [comment]
Fantastic - that's a nicer solution.
Thanks
