### ISSUE TITLE
Exponetiation

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#154]
Here is a implementation of `pow` in Boogie used in the Move prover:

```
// Recursive exponentiation function
// Undefined unless e >=0.  $pow(0,0) is also undefined.
function $pow(n: int, e: int): int {
    if n != 0 && e == 0 then 1
    else if e > 0 then n * $pow(n, e - 1)
    else $undefined_int()
}
```

**Comment by utting** [comment]
That is nice.
What would the specification of this look like?
(I assume we do not have any pre-existing x^y operator in the specification
expressions).

It might be possible to specify the result using a recursive predicate?

This function (with a spec) would be useful when verifying blockchain
contracts...
(2^256 is a pain to write out as a literal integer).

**Comment by DavePearce** [comment]
Hey Mark,

Well, that's it.  I don't think you need to specify it, since this is at the Boogie level.  I guess that it works for the Move prover people, though I haven't tried it yet.  But, I will.  And then I will add the syntax as necessary for writing e.g. `2**256` in Whiley.  Expect it soon!!!

**Comment by DavePearce** [comment]
I should add looking at the Boogie output from Move prover (which was developed in part by Shaz Qadeer) opens up a whole world of opportunities to improve the Boogie backend for Whiley :)

**Comment by DavePearce** [comment]
Ok, this is now implemented in the repository.
