### ISSUE TITLE
Unsoundness of Functions and Constants.

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#21]
This is a placeholder.  The original boogie backend does some things around soundness of axioms for specifications which need to be considered.  Two examples:

## Functions

```
function f() -> (int r)
ensures (2 * r) == 1:
    //
    return 1
```
Basically, we have an axiom `true => (2 * f()) == 1` which shouldn't be permitted.

## Constants
```
nat x = -1

// This function should not be provable.
function f() -> (int r)
ensures r >= 0:
    return x
```

The problem is that, at the current time, there is no check against the type invariant for `x`.

**Comment by DavePearce** [comment]
The fundamental issue here is that the current implementation of `function`s breaks the golden rule:

- **(Golden Rule)**.  User-supplied source should never make it way into an axiom.

The reason behind this rule is that, if the above is allowed, then we can end up with (effectively) `axiom false` and this is the root of all problems.

**Comment by DavePearce** [comment]
To solve the problem for `function`s we need to eliminate the `axiom`.  This is the main root of our problems.   The challenge lies in extracting implicit information from post-conditions (see #28).

**Comment by DavePearce** [comment]
There are two approaches here:

1. Use of `free requires` for function post-conditions.
2. Abandon use of `requires` and `ensures` for `function` implementations and just use `assume` and `assert`.  That way, it's all pretty clear.

**Comment by utting** [comment]
The standard solution to this problem of unsound axioms is to guard the axiom.
This is what Dafny does, and my original Whiley2Boogie adopted this solution for static var init.
See point 5 on page 27 of KRML 190, and Section 4.5.
https://www.microsoft.com/en-us/research/wp-content/uploads/2016/12/krml190.pdf

I think this is a great solution for checking the initialisation of static variables, and for using function axioms within methods.
(However, it does not fully address the soundness issues of recursive functions --- some sort of decreasing measure is still needed within their proofs.)

**Comment by DavePearce** [comment]
Hey Mark,

Right, there are two issues:

1. **(Constants)**.  Actually, these are pretty easy.  There is no real problem with the `axiom` generated for them (it does not break the "golden rule" for example).  The problem is that the type invariant is not itself checked.  We just need a dummy `procedure` which tests whereh the initialiser value meets the type invariant or not.
2. **(Functions)**.  Right, yes.  And I'm just to decide for myself whether or not this is really a general solution.  I was thinking it was not, but perhaps it is.  It seems curious to me that, if we have some axiom that turns out to be `false` (e.g. from a `function f() ensures false`) then that will invade the checking of _all_ functions, even those which do not even call `f()`.

**Comment by utting** [comment]
The CanAssumeFunctionDefs trick is just a way of forcing Boogie to do the whole verification in stages:
Stage 1: verify the bodies of all functions (that they satisfy their specifications).
Stage 2: verify all methods (and we can assume here that all the Stage 1 'axioms' have been proved sound).

Yes, we could do a topological sort of the function call dependency graph, and then have *multiple* verification stages (one per function) instead of just two stages.  (We just make CanAssumeFunctionDefs into an integer, and use axiom guards like CanAssumeFunctionDefs > 8 ==> ...).  This 'stratifies' all the functions, and solves the problems of calls from one function to another.  But we still need some additional technique for handling recursive functions (and mutally recursive).

**Comment by DavePearce** [comment]
Ok, I need to think about it. In particular there needs to be a solution for recursive functions.

Also i’m in New Plymouth next week. So i won’t be doing much on this but I will be on email and perhaps it will give me time to think about this issue more. Really its the only thing stopping us at this stage as far as I can tell.

D

-- 
Associate Professor of Computer Science (Ahonuku),
School of Engineering and Computer Science
Victoria University of Wellington,
PO Box 600,
Wellington,
New Zealand.

He/Him
Cotton 231 (Office)
+64 (0)4 463 5833
http://ecs.victoria.ac.nz/~djp

**Comment by DavePearce** [comment]
Hey,

I’ve been looking at KRML190 a bit now, and it is helping me at least somewhat! There are still issues since Dafny functions and methods correspond very closely with Boogie’s. Still this is good food for thought!!

D

-- 
Associate Professor of Computer Science (Ahonuku),
School of Engineering and Computer Science
Victoria University of Wellington,
PO Box 600,
Wellington,
New Zealand.

He/Him
Cotton 231 (Office)
+64 (0)4 463 5833
http://ecs.victoria.ac.nz/~djp

**Comment by DavePearce** [comment]
Hey Mark,

Ok, well I’m like pointing me at KRML190 has been very helpful —- so thanks for that. I would need to add the CanAssumeFunctionDefs and the corresponding WellDefined functions. However, I cannot see how to rework the WellDefined function for our case. Need to think about that ... hmmm

D

-- 
Associate Professor of Computer Science (Ahonuku),
School of Engineering and Computer Science
Victoria University of Wellington,
PO Box 600,
Wellington,
New Zealand.

He/Him
Cotton 231 (Office)
+64 (0)4 463 5833
http://ecs.victoria.ac.nz/~djp

**Comment by DavePearce** [comment]
A good example which currently verifies (when clearly it should not) is the following:

```
function f() -> (int q)
ensures q >= 0 && q < 0:
    return -1

function g(int x) -> (int y)
ensures y >= 0:
    return x
```

**Comment by DavePearce** [comment]
At this stage, it remains to determine how best to translate the `C.M.WellDefined()` function for checking well-definedness of specifications.  For methods in Dafny, this is roughly translated as follows:

```
assert df(pre)
assume tr(pre)
...
assert df(post)
```

**Comment by DavePearce** [comment]
The main problem here is that `C.M.WellDefined` doesn't prevent the example program above from compiling.

**Comment by DavePearce** [comment]
Another interesting observation is that, for a slight variation, it works fine:

```
function f(int x) -> (int q)
ensures q >= 0 && q < 0:
    return x

function g(int x) -> (int y)
ensures y >= 0:
    return x
```

This example correctly reports errors.  However, I suspect the reason for that is that Z3 simply does not reduce `forall x:int :: false` to `false`.  Potentially in the future it might start doing this.

**Comment by DavePearce** [comment]
**UPDATE:** ok, right, so those to issues above are in fact the same problem.  The issue is that, in both cases, we have effectively `ensures false`.

**Comment by DavePearce** [comment]
There are now at least two solutions to this problem:

1. *(`HEAP`)*  As per issue #75, I'm planning for functions to accept the `HEAP` parameter.  This will simplify the code base in some places, and allow references to be passed into pure functions.
2. *(Satisfiability)*  We can run a satisfiability check for all function post-conditions.  In otherwords, to ensure they are not equivalent to `false`.  This would need to be done assuming `Context#Level == 0` which would restrict the manner in which recursive functions could be used in their specification.

**Comment by DavePearce** [comment]
Ugh.  So, we have a problem here since Boogie cannot verify the following:

```
   assert (exists y:int :: y >= 0);
```

This is obviously true when e.g. `y == 0`.  There's nothing we can do about it!

**Comment by DavePearce** [comment]
**Way Forward?** At this stage, we have now (as far as I can tell) reached a dead-end with the axiom.  There is no real solution to the problems outlined above (though #75 will probably mean it's less of an issue).  The only other approach I can see is to actually remove the axiom altogether, and put in the required assumptions generated from post-conditions manually.  I think this is possible ...

**Comment by utting** [comment]
Interesting. That is what we did in the Alpha version of the boogie
translator. No function axioms, but add

    assert pre
    assume post

Just before each function call.

It sounds like you've got stronger reasons for doing this now?


On the other hand, we don't need to generate an 'exists' proof obligation
for each function postcondition, especially since boogie is not great at
those. We can use the body of the function as the witness, provided its
proof cannot rely on the axiom for that function. (Hence the guards on the
function axioms).

I think either approach will work, but it would be nice to have some good
rationale for one approach over the other, especially for the paper about
this.

Cheers
Mark

**Comment by DavePearce** [comment]
> Interesting. That is what we did in the Alpha version of the boogie translator.

Yeah, I do remember that actually.

> It sounds like you've got stronger reasons for doing this now?

Well, I don't believe there is any other way of doing it that works and retains the semantics of Whiley.  That said, I have just finished implementing #75 and that (by a chance) means the above programs now fail to verify!

> On the other hand, we don't need to generate an 'exists' proof obligation
> for each function postcondition, especially since boogie is not great at
> those. We can use the body of the function as the witness, provided its
> proof cannot rely on the axiom for that function. (Hence the guards on the
> function axioms).

I get what you are saying.  But this comes back to the other discussion we had about methods.  I guess there are two things:

1. **(Allow Recursion)** We retain the semantics of Whiley by using `assert pre` `assume post` within recursive functions.
2. **(No Recursion)** We depart from the semantics of Whiley by not allowing recursive functions to use their specifications.

I don't really see option (2) as being viable.  And, option (1) is fine, but seems like it would be easier to just do that everywhere.  Hmmmmm, _are there any other options ???_

**Comment by DavePearce** [comment]
Haha .... OK!! So, maybe there is one idea that's arising from what you said (unsure if you were thinking of this or not).  What about this:

1. Every `function` has a unique context level.  Then, for a function `f()` with say context-level `1`, the axiom becomes:
```
axiom (Context#Level != 1) ==> f#post(f());
```
2. We add `requires Context#Level != 1` to `f#impl()` above.

At this stage, we just need to translate any recursive invocations of `f()` within `f()` into procedure calls to `f#impl()` (that's ugly), and Boogie will do the rest.

_Does that work?_  No, it doesn't feel quite right ...

Maybe we we need is a flag for each function e.g. `f#welldefined`.  Every function which calls `f()` can then `require f#welldefined`, except for `f#impl` as before.  That's better.

Given that #75 resolves the issue for now, perhaps we should just write about this plan rather than implement (for now).  Or at least provide a discussion of alternatives.
