### ISSUE TITLE
Loop Conditions with Preconditions and SideEffects

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#3]
At the moment, loops are not handled correctly with respect to preconditions and side-effects of the condition.  Specifically, these are extracted on entry to the loop, but then not again at the end of the loop body.

**Comment by utting** [comment]
I just saw a nice solution to this in the KRML190 Dafny paper: put those conditions into the loop invariant.
(That is, just the definedness requirements for the loop condition, not the whole loop condition itself).

This forces Boogie to check those definedness conditions before the loop, but also before the end of the loop body.

E.g. while x[i]<10: S generates Boogie:  while (x[i]<10) invariant 0<=i<len(x) {S}

**Comment by DavePearce** [comment]
Yeah, this makes sense to me and I need get this working!!

**Comment by DavePearce** [comment]
This is subsumed by #74
