### ISSUE TITLE
Problem with Recursive Property?

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#5]
The following simplified version of `Property_Valid_11` is currently failing for reasons unknown:

```
type Node is {int data, List next}
type List is null|Node

property sum(List l, int s)
where (l is null) ==> (s == 0)
where (l is Node) ==> sum(l.next, s - l.data)

method test():
    // List of length 1
    List l1 = {data: 0, next: null}
    //
    assert sum(l1,0)
```

The original `Whiley2Boogie` can verify this though, so I believe it must be possible.

**Comment by DavePearce** [comment]
The minimal boogie code seems to be something like this:

```
// === Begin Preamble ===
type Any;
type Type;
const unique Void : Any;
const unique null : Any;
// Integers
function Int#box(int) returns (Any);
function Int#unbox(Any) returns (int);
axiom (forall i:int :: Int#unbox(Int#box(i)) == i);
axiom (forall i:int :: Int#box(i) != Void);
// Fields
type Field;
const unique $next : Field;
const unique $data : Field;
// Records
function Record#box([Field]Any) returns (Any);
function Record#unbox(Any) returns ([Field]Any);
axiom (forall i:[Field]Any :: Record#unbox(Record#box(i)) == i);
axiom (forall r:[Field]Any :: Record#box(r) != Void);
const unique Record#Empty : [Field]Any;
axiom (forall f:Field :: Record#Empty[f] == Void);
// === End Preamble ===

type Node = [Field]Any;
function Node#is($ : [Field]Any) returns (bool) {
   (List#is($[$next])) && true
}
type List = Any;
function List#is($ : Any) returns (bool) {
   (($ == null) || Node#is(Record#unbox($))) && true
}
function sum(l : List, s : int) returns (bool) {
   ((l == null) ==> (s == 0)) && (Node#is(Record#unbox(l)) ==> sum(Record#unbox(l)[$next],0))
}
procedure test$V$V()
{
   var l1 : List;
   l1 := Record#box(Record#Empty[$data:=Int#box(0)][$next:=null]);
   assert sum(l1,0);
}
```

**Comment by utting** [comment]
This also fails if we set l1:=null;
The problem seems to be that in the Boogie encoding, some values can satisfy *both* of the 'where' guards in the 'sum' definition.
Whereas we really want them to be disjoint.
Perhaps we need to restrict Record#unbox to not work on null?

**Comment by DavePearce** [comment]
Hey Mark,

Yeah, I've encountered some other situations like that and I included some "exclusion" axioms roughly as you did to help with it.  Doesn't seem to solve the problem in this case though, but I need to think about it a bit more.  Am currently stuck in template hell...

**Comment by utting** [comment]
One way I found of solving the problem is to add 'l != null' to the second guard of sum, to ensure that the two branches are disjoint.
That is:
function sum(l : List, s : int) returns (bool) {
   ((l == null) ==> (s == 0)) && ((l != null && Node#is(Record#unbox(l))) ==> sum(Record#unbox(l)[$next],0))
}

But I think a better approach would be to strengthen the axioms about records and null, so that unboxing null gives something that does *not* satisfy any XXX#is(_) predicate. 

I also think it is worth adding an axiom to ensure that any boxed record is not null (like Void):
  axiom (forall r:[Field]Any :: Record#box(r) != null);

What is the intuition behind null vs Void?

**Comment by utting** [comment]
The new disjointness axioms almost solve this issue.
The only extra thing we need is to add Record#is(_) into the definition of Node#is.
Then Boogie can deduce that every Node is a record, so is disjoint from Null.

E.g. changes to add Record#is:
--- Property_Valid_11.bpl       2020-12-21 09:49:42.853000000 +1000
***************
*** 184,186 ****
  function Property_Valid_11$Node$r2I4dataQ4List4next#is($$48 : Any) returns (bool) {
!    (Int#is(Record#unbox($$48)[$data]) && Property_Valid_11$List$u2NQ4Node#is(Record#unbox($$48)[$next])) && Property_Valid_11$Node$r2I4dataQ4List4next#inv(Record#unbox($$48))
  }
--- 184,186 ----
  function Property_Valid_11$Node$r2I4dataQ4List4next#is($$48 : Any) returns (bool) {
!    **Record#is($$48)** && (Int#is(Record#unbox($$48)[$data]) && Property_Valid_11$List$u2NQ4Node#is(Record#unbox($$48)[$next])) && Property_Valid_11$Node$r2I4dataQ4List4next#inv(Record#unbox($$48))
  }



Then it verifies:
$ boogie Property_Valid_11.bpl
Boogie program verifier version 2.8.1.0, Copyright (c) 2003-2014, Microsoft.

Boogie program verifier finished with 1 verified, 0 errors

**Comment by DavePearce** [comment]
Minimal test case is:

```
type Node is {int data, List next}
type List is null|Node

property acyclic(List l)
where (l is Node) ==> acyclic(l.next)

method test():
    // List of length 1
    List l1 = {next: null, data: 123}
    //
    assert acyclic(l1)
```

**Comment by DavePearce** [comment]
See also #53 (which is a duplicate I think)

**Comment by DavePearce** [comment]
Fixed as part of @53
