### ISSUE TITLE
Implement Methods as for Functions

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#76]
Currently, Whiley `method`s are implemented using Boogie procedures.  Instead, they should be split into a functional prototype and a procedure, as for Whiley `function`s.  This is necessary to allow them to be called from arbitrary spots inside an expression.  The challenge remains, however, as to how one threads through the relevant `HEAP` parameter.

**Comment by utting** [comment]
Functions are deterministic, but methods should be able to be non-deterministic.
For example, a readKeyboard() method may return a different result each time we call it.

So I don't think we want to model methods as functions, because that would make Boogie believe that methods are always deterministic.  This would imply that readKeyboard() == readKeyboard(), which is not something we want.

**Comment by DavePearce** [comment]
Hey Mark,

So I agree ... and I disagree!  Yes, they should be non-deterministic.  However, we can model this using Boogie functions (e.g. by including an additional non-deterministic parameter).  The key benefit (I believe) is that we can avoid having to break expressions down into statement sequences.  I'm trying to figure out the easiest translation to solve the remaining outstanding problems.  Maybe this is a good idea, or maybe its not.

However, doing this translation still requires careful handling of the heap.  For example:

```
method m(int a) -> (int b):
  ...

  ...
  int v = m(x+y) +1
  int w = m(v)
```

Then, we can translate directly as a procedure call in Boogie:

```
   call HEAP, tmp := m(HEAP,x+y)
   v = tmp + 1;
   call HEAP, tmp := m(HEAP,v)
   w = tmp;
```

(that's fine)

Or, we can translate it as this:

```
   HEAP#1 = m#1(x+y,HEAP#0,NONCE#0),
   v = m#2(x+y,HEAP#0,NONCE#0) + 1
   HEAP#2 = m#1(v,HEAP#1,NONCE#1),
   w = m#2(v,HEAP#1,NONCE#1)
```

(yes, it's a bit ugly)

Here, `m#1` and `m#2` are the standard mechanism for handling functions with multiple returns (in this case, the updated `HEAP` and the declared return `b`).  Also, `NONCE#0` is a non-deterministic constant to distinguish separate calls to the same method with the same parameters (potentially there's a problem with loops here?)

In the first case, what we end up with doesn't look so much like the original source.  Furthermore, it requires careful handling of short-circuiting (as you've pointed out).  In the second case, well the `HEAP` stuff is ugly ... but, the translation might actually be simpler.

Anyhow, I am trying to weigh up the pros and cons and figure how to solve this final piece of the puzzle!!!!!!

**Comment by DavePearce** [comment]
I should add that, part of this is related to thinking how I would implement the first approach (i.e. breaking expressions down into `CALL` statements).  It's kind of ugly to do it in one pass, especially as we have to generate the precondition checks at the same time.  Maybe I can do it, but I didn't figure out a clean way yet in my head.

**Comment by DavePearce** [comment]
Another option I have been considering is introducing some kind of intermediate language to help with the translation.  This is quite a heavyweight solution, and there are lots of hazards.  Most obvious is that we'd need to design an intermediate language that actually helped with the problem, and this is not easy.  See my attempt at classifying key responsibilities here #74

**Comment by DavePearce** [comment]
To be honest, the easiest solution to my mind would be just to translate everything into three address code with unstructured control-flow.  But, then, what's the point of using Boogie?  You might as well just go straight to Z3.  I'm looking for some kind of "sweet spot", but not had much luck yet.

**Comment by DavePearce** [comment]
Maybe we should have a zoom catch up sometime soon.
