### ISSUE TITLE
Well-Definedness in Specification Elements

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#78]
_(see also #28)_

Currently, well-definedness of specifications is not properly handled for specification elements.  The following illustrates one example:

```
function f(int[] xs) -> (int r)
requires xs[0] >= 0:
    return xs[0]
```

This fails to verify because it cannot conclude that `|xs| > 0` in the body.  If we had this as an _explicit_ precondition then it works.  The solution here is to generate additional requirements from the preconditions themselves, and add them as _implicitly_ preconditions.  This goes also for postconditions, and loop invariants.

**Comment by utting** [comment]
This is a nice idea - it is essentially expanding every precondition P into
df(P) and tf(P).
Where df(P) is the conditions for P to be well-defined, and tf(P) is the
usual true/false value of P.

And similarly for postconditions.
And presumably for loop invariants?  And maybe asserts and assumes?

The only disadvantage I can see is that it might make the generated Boogie
a bit more verbose - it would be nice to not generate the df(P) conditions
that are already implied by the context, but that is probably a pain to
figure out.

Cheers
Mark

**Comment by DavePearce** [comment]
> And similarly for postconditions.
> And presumably for loop invariants?  And maybe asserts and assumes?

Yes, for postconditions and loop invariants.  Hmmmm, not sure about `assert` / `assume`?  Yes, I guess so.

**Comment by DavePearce** [comment]
I am processing this now.

- [ ] Function Requires / Ensures
- [ ] Method Requires / Ensures
- [ ] Loop Invariants
- [ ] Assert  / Assume

**Comment by DavePearce** [comment]
For loop invariants, this is an example:

```
function f(int[] xs) -> (int r)
requires xs[0] == 0:
    //
    int n = 0
    while n < 10 where n >= 0 && xs[0] == 0:
        assert |xs| > 0
        n = n + 1
    //
    return n
```

**Comment by DavePearce** [comment]
Done.  Not for `assert` statements though as I cannot find a test which would fail without.
