### ISSUE TITLE
Type invariant lost in double loop

### ISSUE THREAD

**Issue by utting** [Whiley/Whiley2Boogie#80]
When we have a double-nested loop, and only the inner loop updates an array, then the typing invariant for that array is added to the inner loop, but seems to be needed in the outer loop as well.

For example, this function (which looks artificial, but is a cut-down version of Conways game of life, where the double loop is necessary):
```
public function loop_bug(int width) -> bool[]
requires 0 <= width:
    bool[] ncells = [false; width]
    for x in 0..width:
        for y in 0..width:
            ncells[y] = true
    return ncells
```
adds the invariant to the inner loop:
invariant (forall i#1:int :: (((0 <= i#1) && (i#1 < Array#Length(ncells$85))) ==> Bool#is(ncells$85[i#1])) 
     && (((i#1 < 0) || (Array#Length(ncells$85) <= i#1)) ==> (ncells$85[i#1] == Void)));

But Boogie cannot prove this invariant for each entry to the inner loop.

However, if you manually add that invariant to the outer loop as well, it is much happier.

It still does not quite verify, because it thinks the array length might have changed.
However, this version does verify with Boogie (if you manually copy the inner loop invariant to the outer loop).
```
public function loop_bug(int width) -> bool[]
requires 0 <= width:
    bool[] ncells = [false; width]
    for x in 0..width
    where |ncells| == width:
        for y in 0..width
        where |ncells| == width:
            ncells[y] = true
    return ncells
```

Perhaps the generated array-typing invariant could also say that the length of the array is unchanged?

**Comment by DavePearce** [comment]
> It still does not quite verify, because it thinks the array length might have changed.

That is correct, and is the expected behaviour at this stage.  However, as you point out, it would be nice to avoid this!!  I have an open issue for it (see #68).

**Comment by DavePearce** [comment]
Right, now for the main issue related to the invariant for types on the outer loop.  Actually, the latest version of `Whiley2Boogie` the following passed for me straight away:

```
public function loop_bug(int width) -> (bool[] rs)
requires 0 <= width
ensures |rs| == width:
    bool[] ncells = [false; width]
    //
    for x in 0..width
    where |ncells| == width:
        for y in 0..width
        where |ncells| == width:
            ncells[y] = true
    //
    return ncells
```

Ok, I see what's happened.  I fixed this a couple of weeks ago.  It was actually a bug in `WhileyCompiler` (see [here](https://github.com/Whiley/WhileyCompiler/issues/1053)).  Therefore, you need to update your version of `wyc` to the latest `devel` snapshot.
