### ISSUE TITLE
WellDefinedness of Loop Conditions

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#82]
Currently, well-definedness of loop conditions is not checked properly.  For example, this fails as expected:

```
function count(int[] xs) -> (int r):
    nat i = 0
    //
    while xs[i] > 0:
        i = i + 1
    //
    return i
```

But, this slight variation currently passes:

```
function count(int[] xs) -> (int r)
requires |xs| > 0:
    nat i = 0
    //
    while xs[i] > 0:
        i = i + 1
    //
    return i
```

Clearly, it should not.

**Comment by utting** [comment]
This is the kind of example it would be interesting to discuss in our paper.

If we expand while C to:
   while df(C) && tr(C)

Then this would verify.
And perhaps do what the writer intended?

But if we expand it to:
    while tr(C) when df(C)
Then we would have to verify the definedness on entry and every time around
the loop. Which seems more explicit and safer to me.

Cheers
Mark

**Comment by DavePearce** [comment]
Hey Mark,

The issue is that, at the moment, it doesn't yet translate it as this:

```
 while tr(C) when df(C)
```

This I think is the necessary fix.
