### ISSUE TITLE
Unchecked Precondition

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#84]
The following does not fail for reasons unknown:

```
function f(int[] xs) -> (int r)
requires |xs| > 0
ensures r >= 0 && r <= |xs|:
    //
    return 0

function g(int x) -> (int r)
requires x >= 0 && x < 1:
    //
    return x
    
public export method test():
    //
    assume g(f([0])) == 0
```

The expected error would be:

```
tests/invalid/Array_Invalid_14.whiley:14: precondition may not be satisfied 
    assume g(f([0])) == 0
           ^^^^^^^^^
```

**Comment by DavePearce** [comment]
The issue is that the assume statement is magically allowing it to hold.  Should this be what happens?

**Comment by DavePearce** [comment]
Have reverted the semantics of `assume` so this fails.  For some reason, I think this makes most sense.

**Comment by utting** [comment]
This is an interesting issue.
Should assume P mean:
1. assume df(P); assume tr(P)
2. assert df(P); assume tr(P)

(where df is the conditions for P be well 'defined' and tr is the normal true/false result).
Option 1 seems more 'obvious'?  
But it would magically assume that f([0]) does indeed satisfy the precondition of g.
Option 2 is more conservative.  
Less danger of assuming too much implicitly.
And I guess you can always manually strengthen it by adding the df(P) conditions explicitly before the assume.

Overall, option 2 seems safer, though a little weird to explain to users.
It's not clear to me which approach Dafny takes, though on p26 of KRML190 they make an interesting use of a separate procedure to avoid having to prove df(Pre) at every call site!

**Comment by DavePearce** [comment]
Right, this is exactly the dilemma I've been facing!  And, I think my reasoning is the same.  Basically, option (2) is the more conservative approach.  If we later decide we want to change, it's much easier to go from Option (2) to Option (1) rather than the other way around!
